"""add escalations table

Revision ID: 133274b799d3
Revises: t0u1v2w3x4y5
Create Date: 2026-03-29 00:51:56.680173

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '133274b799d3'
down_revision: str | None = 't0u1v2w3x4y5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('source', sa.Enum('manual', 'auto_error', 'fallback', name='escalation_source'), nullable=False),
    sa.Column('status', sa.Enum('triggered', 'resolved', name='escalation_status'), nullable=False),
    sa.Column('is_technical_error', sa.Boolean(), nullable=False),
    sa.Column('issue_summary', sa.Text(), nullable=True),
    sa.Column('contact_preference', sa.String(length=50), nullable=True),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata_escalation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_escalations_conv_triggered', 'escalations', ['conversation_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_escalations_conversation_id'), 'escalations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_escalations_triggered_at'), 'escalations', ['triggered_at'], unique=False)
    op.drop_index(op.f('idx_appointments_confirmation_pending'), table_name='appointments', postgresql_where="(status = 'pending'::appointment_status)")
    op.drop_index(op.f('idx_appointments_customer_active'), table_name='appointments', postgresql_where="(status = ANY (ARRAY['pending'::appointment_status, 'confirmed'::appointment_status]))")
    op.drop_index(op.f('idx_blocking_events_stylist_id'), table_name='blocking_events')
    op.create_index(op.f('ix_blocking_events_recurring_series_id'), 'blocking_events', ['recurring_series_id'], unique=False)
    op.create_index(op.f('ix_blocking_events_stylist_id'), 'blocking_events', ['stylist_id'], unique=False)
    op.drop_constraint(op.f('uq_conversation_history_conversation_id'), 'conversation_history', type_='unique')
    op.create_index(op.f('ix_conversation_history_conversation_id'), 'conversation_history', ['conversation_id'], unique=True)
    op.drop_index(op.f('ix_conv_messages_chatwoot_id'), table_name='conversation_messages', postgresql_where='(chatwoot_message_id IS NOT NULL)')
    op.create_index(op.f('ix_conversation_messages_chatwoot_message_id'), 'conversation_messages', ['chatwoot_message_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_conversation_history_id'), 'conversation_messages', ['conversation_history_id'], unique=False)
    op.drop_index(op.f('idx_customers_last_service_date'), table_name='customers')
    op.create_index('idx_customers_last_service_date', 'customers', ['last_service_date'], unique=False, postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.drop_index(op.f('idx_gcal_sync_state_stylist_id'), table_name='gcal_sync_state')
    op.drop_constraint(op.f('uq_gcal_sync_state_stylist'), 'gcal_sync_state', type_='unique')
    op.create_index(op.f('ix_gcal_sync_state_stylist_id'), 'gcal_sync_state', ['stylist_id'], unique=True)
    op.drop_constraint(op.f('unique_holiday_date'), 'holidays', type_='unique')
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.drop_index(op.f('idx_notifications_created_at_desc'), table_name='notifications')
    op.create_index('idx_notifications_created_at_desc', 'notifications', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_recurring_blocking_series_stylist_id'), 'recurring_blocking_series', ['stylist_id'], unique=False)
    op.drop_index(op.f('uq_stylists_slug'), table_name='stylists', postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_stylists_slug'), 'stylists', ['slug'], unique=True)
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.drop_index(op.f('idx_settings_history_changed_at'), table_name='system_settings_history')
    op.create_index('idx_settings_history_changed_at', 'system_settings_history', ['changed_at'], unique=False, postgresql_ops={'changed_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_settings_history_changed_at', table_name='system_settings_history', postgresql_ops={'changed_at': 'DESC'})
    op.create_index(op.f('idx_settings_history_changed_at'), 'system_settings_history', [sa.literal_column('changed_at DESC')], unique=False)
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_index(op.f('ix_stylists_slug'), table_name='stylists')
    op.create_index(op.f('uq_stylists_slug'), 'stylists', ['slug'], unique=True, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_recurring_blocking_series_stylist_id'), table_name='recurring_blocking_series')
    op.drop_index('idx_notifications_created_at_desc', table_name='notifications', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('idx_notifications_created_at_desc'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.create_unique_constraint(op.f('unique_holiday_date'), 'holidays', ['date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_gcal_sync_state_stylist_id'), table_name='gcal_sync_state')
    op.create_unique_constraint(op.f('uq_gcal_sync_state_stylist'), 'gcal_sync_state', ['stylist_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_gcal_sync_state_stylist_id'), 'gcal_sync_state', ['stylist_id'], unique=False)
    op.drop_index('idx_customers_last_service_date', table_name='customers', postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.create_index(op.f('idx_customers_last_service_date'), 'customers', [sa.literal_column('last_service_date DESC NULLS LAST')], unique=False)
    op.drop_index(op.f('ix_conversation_messages_conversation_history_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_chatwoot_message_id'), table_name='conversation_messages')
    op.create_index(op.f('ix_conv_messages_chatwoot_id'), 'conversation_messages', ['chatwoot_message_id'], unique=False, postgresql_where='(chatwoot_message_id IS NOT NULL)')
    op.drop_index(op.f('ix_conversation_history_conversation_id'), table_name='conversation_history')
    op.create_unique_constraint(op.f('uq_conversation_history_conversation_id'), 'conversation_history', ['conversation_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_blocking_events_stylist_id'), table_name='blocking_events')
    op.drop_index(op.f('ix_blocking_events_recurring_series_id'), table_name='blocking_events')
    op.create_index(op.f('idx_blocking_events_stylist_id'), 'blocking_events', ['stylist_id'], unique=False)
    op.create_index(op.f('idx_appointments_customer_active'), 'appointments', ['customer_id', 'start_time'], unique=False, postgresql_where="(status = ANY (ARRAY['pending'::appointment_status, 'confirmed'::appointment_status]))")
    op.create_index(op.f('idx_appointments_confirmation_pending'), 'appointments', ['start_time', 'confirmation_sent_at'], unique=False, postgresql_where="(status = 'pending'::appointment_status)")
    op.drop_index(op.f('ix_escalations_triggered_at'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_conversation_id'), table_name='escalations')
    op.drop_index('idx_escalations_conv_triggered', table_name='escalations')
    op.drop_table('escalations')
    # ### end Alembic commands ###
