"""Create core tables: customers, stylists, services, packs

Revision ID: 1a030dcddf99
Revises:
Create Date: 2025-10-26 15:29:17.251862

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a030dcddf99'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Create PostgreSQL extensions
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')

    # Create trigger function for auto-updating updated_at column
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('included_service_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_euros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='check_pack_duration_positive'),
    sa.CheckConstraint('price_euros > 0', name='check_pack_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_packs_included_service_ids', 'packs', ['included_service_ids'], unique=False, postgresql_using='gin')
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('HAIRDRESSING', 'AESTHETICS', 'BOTH', name='service_category'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_euros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requires_advance_payment', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='check_duration_positive'),
    sa.CheckConstraint('price_euros >= 0', name='check_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_services_category_active', 'services', ['category'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_services_name_trgm', 'services', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('stylists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('HAIRDRESSING', 'AESTHETICS', 'BOTH', name='service_category'), nullable=False),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stylists_category_active', 'stylists', ['category'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_stylists_google_calendar_id'), 'stylists', ['google_calendar_id'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_service_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('preferred_stylist_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('length(phone) >= 10', name='check_phone_length'),
    sa.ForeignKeyConstraint(['preferred_stylist_id'], ['stylists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_customers_last_service_date', 'customers', ['last_service_date'], unique=False, postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.create_index(op.f('ix_customers_preferred_stylist_id'), 'customers', ['preferred_stylist_id'], unique=False)
    # ### end Alembic commands ###

    # Apply updated_at triggers to all tables with updated_at column
    tables_with_updated_at = ['packs', 'services', 'stylists']
    for table in tables_with_updated_at:
        op.execute(f"""
            CREATE TRIGGER update_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column();
        """)


def downgrade() -> None:
    # Drop triggers first
    tables_with_updated_at = ['packs', 'services', 'stylists']
    for table in tables_with_updated_at:
        op.execute(f'DROP TRIGGER IF EXISTS update_{table}_updated_at ON {table}')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_preferred_stylist_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index('idx_customers_last_service_date', table_name='customers', postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.drop_table('customers')
    op.drop_index(op.f('ix_stylists_google_calendar_id'), table_name='stylists')
    op.drop_index('idx_stylists_category_active', table_name='stylists', postgresql_where=sa.text('is_active = true'))
    op.drop_table('stylists')
    op.drop_index('idx_services_name_trgm', table_name='services', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('idx_services_category_active', table_name='services', postgresql_where=sa.text('is_active = true'))
    op.drop_table('services')
    op.drop_index('idx_packs_included_service_ids', table_name='packs', postgresql_using='gin')
    op.drop_table('packs')
    # ### end Alembic commands ###

    # Drop trigger function and extensions
    op.execute('DROP FUNCTION IF EXISTS update_updated_at_column()')
    op.execute('DROP EXTENSION IF EXISTS "pg_trgm"')
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')
