"""add_payments_table_and_relationship

Revision ID: 3fd622c382cb
Revises: dc561f2b086e
Create Date: 2025-11-04 12:07:57.797694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fd622c382cb'
down_revision: Union[str, None] = 'dc561f2b086e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create payment_status enum if it doesn't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status') THEN
                CREATE TYPE payment_status AS ENUM ('PENDING', 'CONFIRMED', 'REFUNDED', 'FORFEITED');
            END IF;
        END$$;
    """)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique payment identifier'),
    sa.Column('appointment_id', sa.UUID(), nullable=False, comment='Associated appointment'),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=False, comment='Stripe PaymentIntent ID (pi_xxx)'),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True, comment='Stripe Checkout Session ID (cs_xxx)'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Payment amount in euros (e.g., 15.00 for 15€ deposit)'),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'REFUNDED', 'FORFEITED', name='payment_status', create_type=False), nullable=False, comment='Payment status (pending, succeeded, failed, canceled)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When payment intent was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last status update'),
    sa.Column('stripe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional Stripe webhook data (payment method, receipt URL, etc.)'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_appointment_id', 'payments', ['appointment_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_appointment_id'), 'payments', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_stripe_checkout_session_id'), 'payments', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=True)
    op.drop_index(op.f('idx_conversation_history_timestamp_desc'), table_name='conversation_history')
    op.create_index('idx_conversation_history_timestamp_desc', 'conversation_history', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.drop_index(op.f('idx_customers_last_service_date'), table_name='customers')
    op.create_index('idx_customers_last_service_date', 'customers', ['last_service_date'], unique=False, postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_customers_last_service_date', table_name='customers', postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.create_index(op.f('idx_customers_last_service_date'), 'customers', [sa.literal_column('last_service_date DESC NULLS LAST')], unique=False)
    op.drop_index('idx_conversation_history_timestamp_desc', table_name='conversation_history', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_conversation_history_timestamp_desc'), 'conversation_history', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_checkout_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_appointment_id'), table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_appointment_id', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
