"""add_confirmation_tracking_fields

Revision ID: 62769e850a51
Revises: c4f7e6d9a2b1
Create Date: 2025-11-20 09:53:49.824209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62769e850a51'
down_revision: Union[str, None] = 'c4f7e6d9a2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new tracking fields to appointments
    op.add_column('appointments', sa.Column('confirmation_sent_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('reminder_sent_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('notification_failed', sa.Boolean(), server_default='false', nullable=False))

    # Add chatwoot_conversation_id to customers
    op.add_column('customers', sa.Column('chatwoot_conversation_id', sa.String(length=50), nullable=True))

    # Update AppointmentStatus enum values
    # NOTE: This requires manual ALTER TYPE for PostgreSQL enums
    op.execute("ALTER TYPE appointment_status RENAME VALUE 'provisional' TO 'pending'")
    op.execute("ALTER TYPE appointment_status ADD VALUE IF NOT EXISTS 'no_show'")
    # Remove 'expired' value - not directly supported, but since it's not used we can leave it

    # Add partial indexes for worker queries
    op.execute("""
        CREATE INDEX idx_appointments_confirmation_pending
        ON appointments (start_time, confirmation_sent_at)
        WHERE status = 'pending'
    """)
    op.execute("""
        CREATE INDEX idx_appointments_customer_active
        ON appointments (customer_id, start_time)
        WHERE status IN ('pending', 'confirmed')
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop partial indexes
    op.execute("DROP INDEX IF EXISTS idx_appointments_customer_active")
    op.execute("DROP INDEX IF EXISTS idx_appointments_confirmation_pending")

    # Revert enum changes (PENDING -> PROVISIONAL)
    # NOTE: Cannot remove 'no_show' value from enum without recreating the enum type
    # This is a limitation of PostgreSQL ALTER TYPE
    op.execute("ALTER TYPE appointment_status RENAME VALUE 'pending' TO 'provisional'")

    # Remove new columns
    op.drop_column('customers', 'chatwoot_conversation_id')
    op.drop_column('appointments', 'notification_failed')
    op.drop_column('appointments', 'cancelled_at')
    op.drop_column('appointments', 'reminder_sent_at')
    op.drop_column('appointments', 'confirmation_sent_at')
    # ### end Alembic commands ###
