"""add stripe_payment_link_id to appointments table

Revision ID: dc561f2b086e
Revises: 0088717d25dd
Create Date: 2025-11-04 10:49:25.328340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc561f2b086e'
down_revision: Union[str, None] = '0088717d25dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('stripe_payment_link_id', sa.String(length=255), nullable=True, comment='Stripe Payment Link ID for deactivation on expiration'))
    op.drop_index(op.f('idx_appointments_customer_id'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_status'), table_name='appointments')
    op.drop_index(op.f('idx_appointments_stylist_id'), table_name='appointments')
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_stylist_id'), 'appointments', ['stylist_id'], unique=False)
    op.drop_index(op.f('idx_conversation_history_customer_id'), table_name='conversation_history')
    op.drop_index(op.f('idx_conversation_history_timestamp_desc'), table_name='conversation_history')
    op.create_index('idx_conversation_history_timestamp_desc', 'conversation_history', ['timestamp'], unique=False, postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('ix_conversation_history_customer_id'), 'conversation_history', ['customer_id'], unique=False)
    op.drop_index(op.f('idx_customers_last_service_date'), table_name='customers')
    op.create_index('idx_customers_last_service_date', 'customers', ['last_service_date'], unique=False, postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.create_unique_constraint(None, 'policies', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='unique')
    op.drop_index('idx_customers_last_service_date', table_name='customers', postgresql_ops={'last_service_date': 'DESC NULLS LAST'})
    op.create_index(op.f('idx_customers_last_service_date'), 'customers', [sa.literal_column('last_service_date DESC NULLS LAST')], unique=False)
    op.drop_index(op.f('ix_conversation_history_customer_id'), table_name='conversation_history')
    op.drop_index('idx_conversation_history_timestamp_desc', table_name='conversation_history', postgresql_ops={'timestamp': 'DESC'})
    op.create_index(op.f('idx_conversation_history_timestamp_desc'), 'conversation_history', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_conversation_history_customer_id'), 'conversation_history', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_appointments_stylist_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.create_index(op.f('idx_appointments_stylist_id'), 'appointments', ['stylist_id'], unique=False)
    op.create_index(op.f('idx_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('idx_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('idx_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.drop_column('appointments', 'stripe_payment_link_id')
    # ### end Alembic commands ###
